---
title: 'Project 1: Exploratory Data Analysis'
author: "SDS348 Fall 2019"
date: "10/20/2019"
output:
  html_document:
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: yes
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### Jessica Pak, jp53689

## Data Wrangling and Data Exploration

```{R}
Melanoma<-read.csv("~/Desktop/Melanoma.csv")
biopsy<-read.csv("~/Desktop/biopsy.csv")
library(dplyr)
library(tidyverse)
```
### Introduction

The two datasets I have chosen are 'Melanoma' and 'biopsy.' The Melanoma data frame has data on 205 patients in Denmark with malignant melanoma. The variables in this data frame are 'status,' which indicates whether the patient died from melanoma(1), is alive(2), or died from other causes(3), 'sex,' (1=male,0=female),'age' in years, 'year', 'thickness,' which indicates the thickness of the tumour in mm, and 'ulcer,' which indicates the presence (1) or absence (0) of an ulcer. The biopsy data frame contains data from biopsies of breast tumours for 699 patients. The variables it contains are sample code number, clump thickness, uniformity of cell size, uniformity of cell shape, marginal adhesion, single epithelial cell size, bare nuclei, bland chromatin, normal nucleoli, mitoses, and class. The two dataframes share the variable of tumour thickness. The 'Melanoma dataset was aquired from the R package called 'MASS' and the 'aids' dataset was acquired from the R package called 'boot.' These variables are interesting to me because I am interested in cancer research as well as aids research. Using select I removed the X column from both datasets and the X.1 column from the biopsy dataset.
```{R}
Melanoma<-Melanoma%>%
  select(-X)
biopsy<-biopsy%>%
  select(-X)%>%
  select(-X.1)
glimpse(Melanoma)
glimpse(biopsy)
```
### Tidying: Spread/Gather

Since my datasets were already tidy, I used spread() to untidy the Melanoma dataset and gather() to retidy it. I created a new dataset for the called 'Melwide' using the spread() function. Then I created another new dataset called 'Mellong' using the gather() function. 
```{R}
Melwide<-Melanoma%>%
  spread(key="sex", value="status")
Mellong<-Melwide%>%
  gather(5:6,key = "sex", value = "status", na.rm = T)

```

### Joining/Merging 
    
The Melanoma dataset contains a variable for thickness, however in order for the values to match the values for thickness in the biopsy dataset, I rounded the thickness values in the Melanoma dataset. I then used a full join. No cases in either dataset were dropped. My reason for using full join was to ensure that the 'class' variable from the biopsy dataset was not dropped. I will be removing the other unneccessary variables from the biopsy dataset later. 
```{R}
Melanoma$thickness<-round(Melanoma$thickness)
biopsyMelanoma<-full_join(Melanoma, biopsy, by=c("thickness"="V1"))
```

### Wrangling

Using the joined biopsyMelanoma dataset, I first removed rows with the value '3' in the 'status' variable because 3 indicates death by other causes. Then I changed the catagorical variable 'sex' to Male and Female, changed the catagorical variable 'status' to Died and Alive, and changed the catagorical variable 'ulcer' to present and absent. Then I used filter to remove the rows with NAs from the 'class' variable. Then I removed 8 more variables that using select. Next I used arrange to arrange the rows by age. I used mutate to create a new variable to visualize the clump thickness compared to single epithelial cell size (V5). 

Then I used group_by to group the rows by sex and status, and using summarize I calculated the mean age and standard deviation of single epithelial cell size for sex and status. Using group_by again, I grouped the rows by status and using n_distinct counted the number of distinct years for people who were alive and dead. Next I grouped the rows by class and using summarize found the average thickness for benign and malignant tumours. I grouped by ulcer and found the median of the new variable I created (tumour thickness divided by single epithelial cell size) for the presence and absence of a tumour. Then I grouped by status and found the maximum thickness for alive and dead. Grouping by status, I found the minimum age of patients who are alive and dead. Grouping by sex, I found the mean age of male and female patients. Grouping by status, I found the maximum age of patients who are alive and dead. Grouping by status, I found the total number of males and females who are alive and dead. 
```{R}
biopsyMelanoma<-biopsyMelanoma[biopsyMelanoma$status!=3,]

biopsyMelanoma$sex[biopsyMelanoma$sex==1] <- "Male"
biopsyMelanoma$sex[biopsyMelanoma$sex==0] <- "Female"
biopsyMelanoma$status[biopsyMelanoma$status==1]<- "Died"
biopsyMelanoma$status[biopsyMelanoma$status==2]<- "Alive"
biopsyMelanoma$status[biopsyMelanoma$status==3]<- "Other Causes"
biopsyMelanoma$ulcer[biopsyMelanoma$ulcer==1]<-"present"
biopsyMelanoma$ulcer[biopsyMelanoma$ulcer==0]<-"absent"

biopsyMelanoma<-biopsyMelanoma%>%
  filter((!is.na(class)))%>%
  select(-ID,-V2,-V3,-V4,-V6,-V7,-V8,-V9)%>%
  arrange(age)%>%
  mutate(tumour=thickness/V5)

sexstatusagev5<-biopsyMelanoma%>%
  group_by(sex,status)%>%
  summarize(avgage=mean(age, na.rm = T), sdv5=sd(V5, na.rm = T))
            
statusyeardistinct<-biopsyMelanoma%>%
  group_by(status)%>%
  summarize(nyeardist=n_distinct(year, na.rm = T))

classthickness<-biopsyMelanoma%>%
  group_by(class)%>%
  summarize(meanthickness=mean(thickness, na.rm=T))

ulcertumour<-biopsyMelanoma%>%
  group_by(ulcer)%>%
  summarize(medtumour=median(tumour, na.rm = T))

statusthickness<-biopsyMelanoma%>%
  group_by(status)%>%
  summarize(maxthickness=max(thickness, na.rm = T))

minstatusage<- biopsyMelanoma%>%
  group_by(status)%>%
  summarize(minage=min(age, na.rm = T))

sexavgv5<-biopsyMelanoma%>%
  group_by(sex)%>%
  summarize(meanage=mean(age, na.rm = T))

maxstatusage<-biopsyMelanoma%>%
  group_by(status)%>%
  summarize(maxage=max(age, na.rm = T))

nstatussex<-biopsyMelanoma%>%
  group_by(status)%>%
  count(sex)
```
### Visualizing
The first plot I created is a barplot that shows the thickness of tumours that are benign and malignant for males and females. For both males and females, on average, thicker tumours were malignant and less thick tumours were benign. 

```{R}
library(ggplot2)
ggplot(biopsyMelanoma, aes(x = class, fill=sex))+geom_bar(position="dodge",aes(y=thickness), stat = "summary", fun.y="mean")+ggtitle("Thickness of Tumours by Class and Sex")+theme(axis.text.x = element_text(angle=45, hjust=1))+theme_minimal()+scale_fill_grey()
```

The second plot I created is a barplot that shows the thickness of tumours for patients who are alive and dead for males and females. For both males and females, on average, patients with thicker tumours are dead and patients with less thick tumours are alive. 
   
```{R}
ggplot(biopsyMelanoma, aes(x = status, fill=sex))+geom_bar(position="dodge",aes(y=thickness), stat = "summary", fun.y="mean")+ggtitle("Thickness of Tumours by Status and Sex")+theme_light()+scale_fill_brewer()
```

### Dimensionality Reduction

```{R}
bm_nums<-biopsyMelanoma%>%select_if(is.numeric)%>%scale
rownames(bm_nums)<-biopsyMelanoma$Name
bm_pca<-princomp(bm_nums)
names(bm_pca)
```

```{R}
summary(bm_pca, loadings=T)

eigval<-bm_pca$sdev^2
varprop=round(eigval/sum(eigval),2)
ggplot()+geom_bar(aes(y=varprop,x=1:5),stat="identity")+xlab("")+geom_path(aes(y=varprop,x=1:5))+
  geom_text(aes(x=1:5,y=varprop,label=round(varprop,2)),vjust=1,col="white",size=5)+
  scale_y_continuous(breaks=seq(0,.6,.2),labels = scales::percent)+
  scale_x_continuous(breaks=1:10)

eigval
```

```{R}
bm_df<-data.frame(PC1=bm_pca$scores[,1], PC2=bm_pca$scores[,2], PC3=bm_pca$scores[,3])
ggplot(bm_df,aes(PC1, PC2))+geom_point()
ggplot(bm_df,aes(PC2, PC3))+geom_point()
ggplot(bm_df,aes(PC1, PC3))+geom_point()
```

```{R}
bm_pca$loadings[1:5,1:2]%>%as.data.frame%>%rownames_to_column%>%
ggplot()+geom_hline(aes(yintercept=0),lty=2)+
  geom_vline(aes(xintercept=0),lty=2)+ylab("PC2")+xlab("PC1")+
  geom_segment(aes(x=0,y=0,xend=Comp.1,yend=Comp.2),arrow=arrow(),col="red")+
  geom_label(aes(x=Comp.1*.9,y=Comp.2+.1,label=rowname))

```

With the full biopsyMelanoma dataset I cleaned the data by grabing all numerics. Then I normalized the data (scaled to mean=0, sd=1). Then I ran princomp() on the scaled data. To decide how many components to keep, I plotred the proportion of variance explained by each principal component (from largest eigenvalue to smallest). I did this by squaring to convert SDs to eigenvalues, then finding the proportion of var explained by each PC. After running 'eigval' I decided to only keep Comp.1, Comp.2, and Comp.3 because these are the PCs whose eigenvalues are greater than 1. According to the results, PC1 seems to be a general unwellness factor since all events load positively on this component. PC2 seems to indicate age,tumour thickness, and single epithelial cell size vs. thickness/single epithelial cell size. PC3; seems to indicate year, age, and thickness/epithelial cell size vs. thickness and single epithelial cell size. PC1, PC2, and PC3 account for 84% of the total variance. 3 PCs have eigen values greater than 1. Year is slightly negatively correlated with other variables (which makes sense). However, age, single epithelial cell size, thickness, and tumour are all positively correlated. 


